name: Build Standalone

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows .exe bauen
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl pyinstaller pillow

      - name: .exe erzeugen
        run: |
          pyinstaller --onefile --windowed \
            --name ExcelSearcher \
            --add-data "logo.jpg;." \
            --hidden-import PIL \
            --hidden-import PIL.Image \
            --hidden-import PIL.ImageTk \
            search_excel.py

      - name: .exe als Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: search_excel-windows
          path: dist/ExcelSearcher.exe

  build-macos:
    name: macOS .app-Bundle bauen
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pandas openpyxl pyinstaller pillow

      - name: .app-Bundle erzeugen
        run: |
          pyinstaller --windowed \
            --name ExcelSearcher.app \
            --add-data "logo.jpg:Resources" \
            --hidden-import PIL \
            --hidden-import PIL.Image \
            --hidden-import PIL.ImageTk \
            search_excel.py

      - name: .app komplett zippen
        run: |
          cd dist
          zip -r ../search_excel-macos.zip ExcelSearcher.app

      - name: ZIP-Artefakt hochladen
        uses: actions/upload-artifact@v4
        with:
          name: search_excel-macos
          path: search_excel-macos.zip
